# Generated by Django 5.1.4 on 2025-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Daun', max_length=30),
        ),
    ]
