# Generated by Django 5.1.4 on 2025-08-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
    ]
