# Generated by Django 5.1.4 on 2025-08-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
