# Generated by Django 5.2.5 on 2025-08-10 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_problem', models.CharField(max_length=150, verbose_name='Задача')),
                ('mess_problem', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
                ('deadlines', models.DateTimeField(blank=True, default='Не срочное', null=True, verbose_name='Крайний срок')),
                ('status', models.CharField(choices=[('not accepted', 'Ожидает'), ('at work', 'В работе'), ('completed', 'Готова'), ('cancelled', 'Отменена')], max_length=150, verbose_name='Статус')),
                ('value', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Очки за выполнение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
