# Generated by Django 5.1.4 on 2025-08-25 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='media/group_avatar/default.png', null=True, upload_to='media/group_avatar/')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('descripion', models.TextField(blank=True, max_length='200', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
