# Generated by Django 5.1.4 on 2025-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='descripion',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='description',
            field=models.TextField(blank=True, max_length='200', null=True),
        ),
    ]
