# Generated by Django 5.1.4 on 2025-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_groupchat_descripion_groupchat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='icon',
            field=models.ImageField(blank=True, default='group_avatar/default.png', null=True, upload_to='group_avatar/'),
        ),
    ]
