# Generated by Django 5.1.4 on 2025-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_groupchat_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='icon',
            field=models.ImageField(blank=True, default='group_avatar/default.png', null=True, upload_to='group_avatar'),
        ),
    ]
